[build-system]
requires = [
    "setuptools",
    "tomli; python_version >= '3' and python_version < '3.11'",
    "toml; python_version < '3'",
    "packaging",
]

[tool.build_manpages]
manpages = [
    "some-file.1:pyfile=some-file:function=get_parser",
]
