#! /bin/sh

# Copyright (C) 2017 Red Hat, Inc.

srcdir=$(readlink -f "$(dirname "$0")")
script_name=$(basename "$0")
export PYTHONPATH=$srcdir/${PYTHONPATH+:$PYTHONPATH}
exec "$srcdir/bin/$script_name" "$@"
