.TH RESALLOC-MAINT "1" Manual
.SH NAME
resalloc-maint
.SH SYNOPSIS
.B resalloc-maint
[-h] [--duh DUH] {resource-list,resource-delete,ticket-list} ...
.SH OPTIONS
.TP
\fB\-\-duh\fR \fI\,DUH\/\fR
huhh

.SH
ACTIONS
.TP
\fBresalloc-maint\fR \fI\,resource-list\/\fR
List available resources
.TP
\fBresalloc-maint\fR \fI\,resource-delete\/\fR
Delete resource
.TP
\fBresalloc-maint\fR \fI\,ticket-list\/\fR
List not-yet-closed tickets
.SH COMMAND \fI\,'resalloc-maint resource-list'\/\fR
usage: resalloc-maint resource-list [-h] [--up]

.SH OPTIONS \fI\,'resalloc-maint resource-list'\/\fR
.TP
\fB\-\-up\fR
List only ready\-to\-take resources

.SH COMMAND \fI\,'resalloc-maint resource-delete'\/\fR
usage: resalloc-maint resource-delete [-h] resource

.TP
\fBresource\fR
The resource ID

.SH COMMAND \fI\,'resalloc-maint ticket-list'\/\fR
usage: resalloc-maint ticket-list [-h]

.SH AUTHORS
.nf
Pavel Raiskup <praiskup@redhat.com>
.fi

.SH DISTRIBUTION
The latest version of resalloc may be downloaded from
.UR https://github.com/praiskup/resalloc
.UE
