.TH example 1 2017\-09\-24 "example v.0.1.0.dev0"
.SH NAME
example \- This script does nothing.
.SH SYNOPSIS
.B example
The usage.
.SH DESCRIPTION
Description and long description are both used by build_manpage.
.SH OPTIONS
.TP
.B \-h, \-\-help
show this help message and exit
.TP
.B \-f FILE, \-\-file=FILE
write report to FILE
.TP
.B \-q, \-\-quiet
don't print status messages to stdout
.SH AUTHORS
.B example
was written by John Doe <jd@example.com>.
.SH DISTRIBUTION
The latest version of example may be downloaded from
.UR http://example.com
.UE
